# Example: Agentic Bug Fix Workflow
#
# This workflow demonstrates how an AI agent can autonomously fix bugs
# using context assembled by coding-context-cli.

name: Agentic Bug Fix

on:
  issues:
    types: [labeled]

jobs:
  auto-fix:
    # Only run when a 'bug' label is added
    if: contains(github.event.issue.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Coding Context CLI
        run: |
          curl -fsL -o /usr/local/bin/coding-context-cli \
            https://github.com/kitproj/coding-context-cli/releases/latest/download/coding-context-cli_linux_amd64
          chmod +x /usr/local/bin/coding-context-cli
      
      - name: Determine Bug Severity
        id: severity
        run: |
          # Check for severity labels
          SEVERITY="medium"  # default
          if echo "${{ toJSON(github.event.issue.labels.*.name) }}" | grep -q "critical"; then
            SEVERITY="critical"
          elif echo "${{ toJSON(github.event.issue.labels.*.name) }}" | grep -q "high"; then
            SEVERITY="high"
          elif echo "${{ toJSON(github.event.issue.labels.*.name) }}" | grep -q "low"; then
            SEVERITY="low"
          fi
          echo "severity=$SEVERITY" >> $GITHUB_OUTPUT
      
      - name: Assemble Bug Fix Context
        run: |
          # Assemble context with issue-specific information
          coding-context-cli \
            -s task=fix-bug \
            -s severity=${{ steps.severity.outputs.severity }} \
            -p issue_number=${{ github.event.issue.number }} \
            -p issue_title="${{ github.event.issue.title }}" \
            -p issue_url="${{ github.event.issue.html_url }}" \
            -p issue_body="${{ github.event.issue.body }}" \
            fix-bug > bugfix-context.txt
      
      - name: Create Fix Branch
        run: |
          BRANCH_NAME="ai/fix-issue-${{ github.event.issue.number }}"
          git checkout -b $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
      
      - name: Execute AI Bug Fix
        uses: your-org/ai-agent-action@v1
        with:
          context-file: bugfix-context.txt
          task: implement-fix
          model: claude-3-5-sonnet-20241022
          max-iterations: 5  # Allow multiple attempts
          verify: true  # Run tests to verify fix
      
      - name: Commit Changes
        id: commit
        run: |
          git config user.name "AI Agent"
          git config user.email "ai-agent@example.com"
          
          if [[ -n $(git status -s) ]]; then
            git add .
            cat << 'EOF' | git commit -F -
          Fix: Automated fix for issue #${{ github.event.issue.number }}
          
          This fix was automatically generated by an AI agent.
          
          Issue: ${{ github.event.issue.title }}
          Severity: ${{ steps.severity.outputs.severity }}
          
          Closes #${{ github.event.issue.number }}
          EOF
            
            git push origin ${{ env.branch_name }}
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.commit.outputs.has_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = ${{ github.event.issue.number }};
            const issueTitle = `${{ github.event.issue.title }}`;
            const severity = '${{ steps.severity.outputs.severity }}';
            const issueUrl = '${{ github.event.issue.html_url }}';
            const branchName = '${{ env.branch_name }}';
            
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[AI] Fix for issue #${issueNumber}: ${issueTitle}`,
              head: branchName,
              base: 'main',
              body: `## Automated Fix
              
              This PR was automatically created by an AI agent to fix issue #${issueNumber}.
              
              ### Issue Details
              - **Title**: ${issueTitle}
              - **Severity**: ${severity}
              - **Link**: ${issueUrl}
              
              ### What Changed
              The AI agent analyzed the issue and implemented a fix. Please review the changes carefully before merging.
              
              ### Verification
              - [x] AI agent validated the fix
              - [ ] Human review required
              - [ ] Integration tests passed
              
              Closes #${issueNumber}`
            });
            
            // Add labels to the PR
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.data.number,
              labels: ['ai-generated', 'bug-fix', severity]
            });
            
            // Comment on the original issue
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: `🤖 I've created PR #${pr.data.number} with a potential fix. Please review!`
            });
      
      - name: Report Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: `⚠️ The AI agent was unable to automatically fix this issue. Manual intervention required.
              
              Please check the [workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId}) for details.`
            });
