# Example: Multi-Stage Agentic Feature Development
#
# This workflow demonstrates how to use coding-context-cli across
# multiple stages of feature development with different contexts.

name: Agentic Feature Development

on:
  workflow_dispatch:
    inputs:
      feature_name:
        description: 'Feature name'
        required: true
        type: string
      feature_description:
        description: 'Feature description'
        required: true
        type: string
      priority:
        description: 'Feature priority'
        required: true
        type: choice
        options:
          - low
          - medium
          - high
          - critical

jobs:
  plan:
    name: Planning Phase
    runs-on: ubuntu-latest
    outputs:
      plan_file: ${{ steps.plan.outputs.file }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Coding Context CLI
        run: |
          curl -fsL -o /usr/local/bin/coding-context-cli \
            https://github.com/kitproj/coding-context-cli/releases/latest/download/coding-context-cli_linux_amd64
          chmod +x /usr/local/bin/coding-context-cli
      
      - name: Assemble Planning Context
        run: |
          coding-context-cli \
            -s stage=planning \
            -s priority=${{ inputs.priority }} \
            -p feature_name="${{ inputs.feature_name }}" \
            -p feature_description="${{ inputs.feature_description }}" \
            plan-feature > planning-context.txt
      
      - name: Generate Feature Plan
        id: plan
        uses: your-org/ai-agent-action@v1
        with:
          context-file: planning-context.txt
          task: create-plan
          model: claude-3-5-sonnet-20241022
          output-file: feature-plan.md
      
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: feature-plan
          path: feature-plan.md
  
  implement:
    name: Implementation Phase
    needs: plan
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.branch.outputs.name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: feature-plan
      
      - name: Install Coding Context CLI
        run: |
          curl -fsL -o /usr/local/bin/coding-context-cli \
            https://github.com/kitproj/coding-context-cli/releases/latest/download/coding-context-cli_linux_amd64
          chmod +x /usr/local/bin/coding-context-cli
      
      - name: Create Feature Branch
        id: branch
        run: |
          BRANCH_NAME="ai/feature-$(echo '${{ inputs.feature_name }}' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')"
          git checkout -b $BRANCH_NAME
          echo "name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      
      - name: Assemble Implementation Context
        run: |
          # Include the plan in the context
          PLAN_CONTENT=$(cat feature-plan.md)
          
          coding-context-cli \
            -s stage=implementation \
            -s priority=${{ inputs.priority }} \
            -p feature_name="${{ inputs.feature_name }}" \
            -p feature_description="${{ inputs.feature_description }}" \
            -p feature_plan="$PLAN_CONTENT" \
            implement-feature > implementation-context.txt
      
      - name: Implement Feature
        uses: your-org/ai-agent-action@v1
        with:
          context-file: implementation-context.txt
          task: write-code
          model: claude-3-5-sonnet-20241022
          max-tokens: 16000
      
      - name: Commit Implementation
        run: |
          git config user.name "AI Agent"
          git config user.email "ai-agent@example.com"
          git add .
          git commit -m "feat: Implement ${{ inputs.feature_name }}
          
          This implementation was automatically generated by an AI agent.
          
          Priority: ${{ inputs.priority }}"
          git push origin ${{ steps.branch.outputs.name }}
  
  test:
    name: Testing Phase
    needs: implement
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.implement.outputs.branch_name }}
      
      - name: Install Coding Context CLI
        run: |
          curl -fsL -o /usr/local/bin/coding-context-cli \
            https://github.com/kitproj/coding-context-cli/releases/latest/download/coding-context-cli_linux_amd64
          chmod +x /usr/local/bin/coding-context-cli
      
      - name: Assemble Testing Context
        run: |
          coding-context-cli \
            -s stage=testing \
            -s priority=${{ inputs.priority }} \
            -p feature_name="${{ inputs.feature_name }}" \
            test-feature > testing-context.txt
      
      - name: Generate Tests
        uses: your-org/ai-agent-action@v1
        with:
          context-file: testing-context.txt
          task: write-tests
          model: claude-3-5-sonnet-20241022
      
      - name: Run Tests
        run: |
          # This would run your actual test suite
          # For example: npm test, go test, pytest, etc.
          echo "Running tests..."
      
      - name: Commit Tests
        run: |
          git config user.name "AI Agent"
          git config user.email "ai-agent@example.com"
          
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "test: Add tests for ${{ inputs.feature_name }}"
            git push origin ${{ needs.implement.outputs.branch_name }}
          fi
  
  review:
    name: Review and Documentation
    needs: [implement, test]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.implement.outputs.branch_name }}
      
      - name: Install Coding Context CLI
        run: |
          curl -fsL -o /usr/local/bin/coding-context-cli \
            https://github.com/kitproj/coding-context-cli/releases/latest/download/coding-context-cli_linux_amd64
          chmod +x /usr/local/bin/coding-context-cli
      
      - name: Assemble Documentation Context
        run: |
          coding-context-cli \
            -s stage=documentation \
            -p feature_name="${{ inputs.feature_name }}" \
            -p feature_description="${{ inputs.feature_description }}" \
            document-feature > documentation-context.txt
      
      - name: Generate Documentation
        uses: your-org/ai-agent-action@v1
        with:
          context-file: documentation-context.txt
          task: write-docs
          model: claude-3-5-sonnet-20241022
      
      - name: Commit Documentation
        run: |
          git config user.name "AI Agent"
          git config user.email "ai-agent@example.com"
          
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "docs: Add documentation for ${{ inputs.feature_name }}"
            git push origin ${{ needs.implement.outputs.branch_name }}
          fi
      
      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[AI] Feature: ${{ inputs.feature_name }}`,
              head: '${{ needs.implement.outputs.branch_name }}',
              base: 'main',
              body: `## 🤖 AI-Generated Feature
              
              This feature was developed autonomously by an AI agent across multiple stages.
              
              ### Feature Details
              - **Name**: ${{ inputs.feature_name }}
              - **Description**: ${{ inputs.feature_description }}
              - **Priority**: ${{ inputs.priority }}
              
              ### Development Stages
              - [x] Planning - Feature design and architecture
              - [x] Implementation - Code written
              - [x] Testing - Tests generated and passing
              - [x] Documentation - Docs updated
              
              ### Review Checklist
              - [ ] Code quality meets standards
              - [ ] Tests provide adequate coverage
              - [ ] Documentation is clear and complete
              - [ ] No security vulnerabilities introduced
              - [ ] Performance is acceptable
              
              ### Agent Workflow
              This PR was created by the [Agentic Feature Development workflow](${context.payload.repository.html_url}/actions/runs/${context.runId}).`
            });
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.data.number,
              labels: ['ai-generated', 'feature', '${{ inputs.priority }}']
            });
